name: Erlang CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24

    - name: Setup rebar3
      run: |
        wget https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        # sudo mv rebar3 /usr/local/bin/
        # pwd

    - name: Run Dialyzer
      run: |
        rebar3
        # rebar3 install
        # rebar3 compile
        # dialyzer --check_plt --plt _build/default/rebar3_24.2.1_plt



